### 1. Auth hello through gateway
GET http://localhost:8080/auth/hello

### 2. Login through gateway
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "123456"
}

### 3. Create project with token
POST http://localhost:8080/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImlhdCI6MTc3NjUyNjE0MywiZXhwIjoxNzc2NjEyNTQzfQ.fedKEl4Sr6c5KUMgNxxKCcvy48HkU6dewHaXzpBAFA0
Content-Type: application/json

{
  "name": "JWT Project",
  "description": "Created from token user"
}

### 4. Get projects with token
GET http://localhost:8080/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImlhdCI6MTc3NjUyNjE0MywiZXhwIjoxNzc2NjEyNTQzfQ.fedKEl4Sr6c5KUMgNxxKCcvy48HkU6dewHaXzpBAFA0

### 5. Create task with token
POST http://localhost:8080/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImlhdCI6MTc3NjUyNjE0MywiZXhwIjoxNzc2NjEyNTQzfQ.fedKEl4Sr6c5KUMgNxxKCcvy48HkU6dewHaXzpBAFA0
Content-Type: application/json

{
  "title": "JWT Task",
  "description": "Task from token user",
  "status": "TODO",
  "priority": "HIGH",
  "assigneeId": 1,
  "projectId": 1
}

### 6. Get tasks with token
GET http://localhost:8080/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImlhdCI6MTc3NjUyNjE0MywiZXhwIjoxNzc2NjEyNTQzfQ.fedKEl4Sr6c5KUMgNxxKCcvy48HkU6dewHaXzpBAFA0

### 7. Create comment with token
POST http://localhost:8080/comments
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImlhdCI6MTc3NjUyNjE0MywiZXhwIjoxNzc2NjEyNTQzfQ.fedKEl4Sr6c5KUMgNxxKCcvy48HkU6dewHaXzpBAFA0
Content-Type: application/json

{
  "content": "Comment from token user",
  "taskId": 1
}

### 8. Get comments by task with token
GET http://localhost:8080/comments/by-task/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImlhdCI6MTc3NjUyNjE0MywiZXhwIjoxNzc2NjEyNTQzfQ.fedKEl4Sr6c5KUMgNxxKCcvy48HkU6dewHaXzpBAFA0

### 9. Get project by id with token
GET http://localhost:8080/projects/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImlhdCI6MTc3NjcwOTQxOSwiZXhwIjoxNzc2Nzk1ODE5fQ.dxfk_jgk8KvRr4y3BQKS315GohOjax2qtYb5BSrTY1Q

### 10. Get task by id with token
GET http://localhost:8080/tasks/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImlhdCI6MTc3NjcwOTQxOSwiZXhwIjoxNzc2Nzk1ODE5fQ.dxfk_jgk8KvRr4y3BQKS315GohOjax2qtYb5BSrTY1Q

### 11. Update task status with token
PATCH http://localhost:8080/tasks/1/status
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImlhdCI6MTc3NjcwOTQxOSwiZXhwIjoxNzc2Nzk1ODE5fQ.dxfk_jgk8KvRr4y3BQKS315GohOjax2qtYb5BSrTY1Q
Content-Type: application/json

{
  "status": "DONE"
}

### 12. Delete task with token
DELETE http://localhost:8080/tasks/3
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImlhdCI6MTc3NjcwOTQxOSwiZXhwIjoxNzc2Nzk1ODE5fQ.dxfk_jgk8KvRr4y3BQKS315GohOjax2qtYb5BSrTY1Q


### 13. Update project with token
PUT http://localhost:8080/projects/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImlhdCI6MTc3Njc5NzAyNiwiZXhwIjoxNzc2ODgzNDI2fQ.Q9PkITdrqgRWt0I64pNedHq2MVp1k3vzO3YBXFSvFNQ
Content-Type: application/json

{
  "name": "Updated Project",
  "description": "Updated description"
}

### 14. Create temp project for delete
POST http://localhost:8080/projects
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImlhdCI6MTc3Njc5NzAyNiwiZXhwIjoxNzc2ODgzNDI2fQ.Q9PkITdrqgRWt0I64pNedHq2MVp1k3vzO3YBXFSvFNQ
Content-Type: application/json

{
  "name": "Project to delete",
  "description": "Temporary project"
}

### 15. Delete temp project
DELETE http://localhost:8080/projects/5
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImlhdCI6MTc3Njc5NzAyNiwiZXhwIjoxNzc2ODgzNDI2fQ.Q9PkITdrqgRWt0I64pNedHq2MVp1k3vzO3YBXFSvFNQ

### 16. Get deleted project
GET http://localhost:8080/projects/5
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImlhdCI6MTc3Njc5NzAyNiwiZXhwIjoxNzc2ODgzNDI2fQ.Q9PkITdrqgRWt0I64pNedHq2MVp1k3vzO3YBXFSvFNQ

### 17. Update task with token
PUT http://localhost:8080/tasks/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImlhdCI6MTc3Njc5NzAyNiwiZXhwIjoxNzc2ODgzNDI2fQ.Q9PkITdrqgRWt0I64pNedHq2MVp1k3vzO3YBXFSvFNQ
Content-Type: application/json

{
  "title": "Updated Task",
  "description": "Updated task description",
  "status": "IN_PROGRESS",
  "priority": "MEDIUM",
  "assigneeId": 1,
  "projectId": 1
}

### 18. Get updated task
GET http://localhost:8080/tasks/1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0dXNlciIsImlhdCI6MTc3Njc5NzAyNiwiZXhwIjoxNzc2ODgzNDI2fQ.Q9PkITdrqgRWt0I64pNedHq2MVp1k3vzO3YBXFSvFNQ