server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service-container:8081
          predicates:
            - Path=/auth/**

        - id: task-service
          uri: http://task-service-container:8082
          predicates:
            - Path=/projects/**,/tasks/**,/comments/**,/secure/**

management:
  endpoints:
    web:
      exposure:
        include: health,info